# dotfile-rs config for tmux config files

name = "tmux"
description = "tmux dotfile config"

validation_commands = [
  ["tmux", "--version"],
]

[[configs]]
name = "main tmux config"
path = ".tmux.conf"

[configs.install_location]
linux = "~/.tmux.conf"
macos = "~/.tmux.conf"
