# dotfile-rs config for helix config files

name = "aws"
description = "AWS dotfile config"

validation_commands = [
  ["aws", "--version"],    
]

[[configs]]
name = "main AWS config"
path = "config"

[configs.install_location]
linux = "~/.aws/config"
macos = "~/.aws/config"
