# Starship toml configuration for EDToaster

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format    = """
$time\
$hostname\
$directory\n\
${custom.bws}\
$character\
"""

[hostname]
style  = 'bold green'
format = '[@dev-pdx]($style) '

[time]
disabled = false
format   = '[$time](bold cyan) '

[directory]
truncation_length = 32
truncation_symbol = '…/'
style = 'cyan'

[character]
success_symbol = '[❯](bold green)[❯](bold cyan)'
error_symbol = '[❯❯](bold red)'
vimcmd_symbol = '[❮❮](bold purple)'

[custom.bws]
command = 'basename $(dirname $(upfind . -name packageInfo))'
format  = '[$output](bold italic purple) '
when    = 'basename $(dirname $(upfind . -name packageInfo))'
