# Helix editor config for EDToaster
# Meant to be symlinked at ~/.config/helix/config.toml for Linux/MacOS
# or at %AppData%\helix\config.toml

theme = "tokyonight_storm"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"