# Helix editor config for EDToaster
# Meant to be symlinked at ~/.config/helix/config.toml for Linux/MacOS
# or at %AppData%\helix\config.toml

theme = "catppuccin_frappe"

[editor]
# Change line numbers to relative in non-insert mode
line-number = "relative"
bufferline  = "multiple"
true-color  = true

# Set default shell for pipe, sh, insert-output, etc.
shell = ["zsh", "-c"]

end-of-line-diagnostics = "hint"

[keys.normal]
# Allow <esc> to collapse selection
esc = ["collapse_selection", "keep_primary_selection"]

# Unbind default movement keys and bind new ones
h   = "no_op"
j   = "no_op"
k   = "move_char_left"
l   = "move_line_down"
";" = "move_line_up"
"'" = "move_char_right"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.file-picker]
# hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal.space]
m = ":toggle-option soft-wrap.enable"
z = [
  "goto_first_nonwhitespace",
  "extend_to_line_end",
  ":pipe-to xargs -I {} -- zellij r -f -- zsh -c '{}'"
]

# Only works in non-windows environments :(
e = ":open %sh{~/.config/helix/yazi-picker.sh '%{buffer_name}'}"
