# Helix editor config for EDToaster
# Meant to be symlinked at ~/.config/helix/config.toml for Linux/MacOS
# or at %AppData%\helix\config.toml

theme = "everocean"

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"