# Helix editor config for EDToaster
# Meant to be symlinked at ~/.config/helix/config.toml for Linux/MacOS
# or at %AppData%\helix\config.toml

theme = "everocean"

[editor]
# Change line numbers to relative in non-insert mode
line-number = "relative"
bufferline  = "multiple"
true-color  = true

shell       = ["zsh", "-c"]

[keys.normal]
# Allow <esc> to collapse selection
esc         = ["collapse_selection", "keep_primary_selection"]

# Unbind default movement keys and bind new ones
h           = "no_op"
j           = "no_op"
k           = "move_char_left"
l           = "move_line_down"
";"         = "move_line_up"
"'"         = "move_char_right"

[editor.cursor-shape]
insert      = "bar"
normal      = "block"
select      = "underline"

[editor.file-picker]
hidden      = false