# dotfile-rs config for helix config files

name = "hx"
description = "Helix dotfile config"

validation_commands = [
  ["hx", "--version"]
]

optional_validation_commands = [
  ["zellij", "--version"],
  ["yazi", "--version"]
]

[[configs]]
name = "main helix config"
path = "config.toml"
install_location = { windows = "$APPDATA\\helix\\config.toml", linux = "~/.config/helix/config.toml", macos = "~/.config/helix/config.toml" }

[[configs]]
name = "everocean theme"
path = "themes/everocean.toml"
install_location = { windows = "$APPDATA\\helix\\themes\\everocean.toml", linux = "~/.config/helix/themes/everocean.toml", macos = "~/.config/helix/themes/everocean.toml" }

[[configs]]
name = "yazi-picker"
path = "yazi-picker.sh"
install_location = { windows = "$APPDATA\\helix\\yazi-picker.sh", linux = "~/.config/helix/yazi-picker.sh", macos = "~/.config/helix/yazi-picker.sh" }

