# dotfile-rs config for helix config files

name = "hx"
description = "Helix dotfile config"

[[configs]]
name = "main helix config"
path = "config.toml"

[configs.install_location]
windows = "$APPDATA\\helix\\config.toml"
linux = "~/.config/helix/config.toml"
macos = "~/.config/helix/config.toml"

[[configs]]
name = "everocean theme"
path = "themes/everocean.toml"

[configs.install_location]
windows = "$APPDATA\\helix\\themes\\everocean.toml"
linux = "~/.config/helix/themes/everocean.toml"
macos = "~/.config/helix/themes/everocean.toml"
